steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-f', 'Dockerfile', '-t', '${_IMAGE}', '.']
  - name: gcr.io/cloud-builders/docker
    args: ['push', '${_IMAGE}']
images:
  - '${_IMAGE}'
options:
  logging: CLOUD_LOGGING_ONLY
